### ISSUE TITLE
Shall we archive this repository?

### ISSUE THREAD

**Issue by rsimha** [ampproject/amp-closure-compiler#91]
AMP no longer uses closure compiler for minification, and is likely to stop using it for type checking in the near future. https://github.com/ampproject/amphtml/issues/35264

In light of this, shall we stop development on this repository and archive it?

/cc @kristoferbaxter @samouri @jridgewell @ampproject/wg-infra

**Comment by kristoferbaxter** [comment]
Makes sense to me!

**Comment by rsimha** [comment]
All `@ampproject/google-closure-compiler*` npm packages have been deprecated. Archiving this repo now.
